if Rails.env == "production"
  # Flickr
  FLICKR_APPLICATION_API_KEY  = ENV["FLICKR_APPLICATION_API_KEY"]
  FLICKR_APPLICATION_SECRET   = ENV["FLICKR_APPLICATION_SECRET"]

  # Facebook
  FACEBOOK_APPLICATION_ID       = ENV["FACEBOOK_APPLICATION_ID"]
  FACEBOOK_APPLICATION_SECRET   = ENV["FACEBOOK_APPLICATION_SECRET"]
  FACEBOOK_APPLICATION_API_KEY  = ENV["FACEBOOK_APPLICATION_API_KEY"]
  FACEBOOK_CALLBACK_URL         = ENV["FACEBOOK_CALLBACK_URL"]

  # Instagram
  INSTAGRAM_CLIENT_ID     = ENV["INSTAGRAM_CLIENT_ID"]
  INSTAGRAM_CLIENT_SECRET = ENV["INSTAGRAM_CLIENT_SECRET"]
  INSTAGRAM_CALLBACK_URL  = ENV["INSTAGRAM_CALLBACK_URL"]
end